adding gregory to open-services-group
open-services-group/community pull request #101
Opened 2022-03-16 21:02 UTC by Gregory-Pereira

requesting access to open-services-group.

2022-03-16 21:03 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **goern** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @goern` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=open-services-group%2Fcommunity).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/open-services-group/community/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["goern"]} -->

2022-03-16 21:03 UTC, sesheta commented
Hi @Gregory-Pereira. Thanks for your PR.

I'm waiting for a [open-services-group](https://github.com/orgs/open-services-group/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/open-services-group/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=open-services-group%2Fcommunity).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-03-17 09:51 UTC, harshad16 requested changes
lgtm
however please set it in alphabetical order.

2022-03-18 09:13 UTC, harshad16 approved these changes
lgtm
thanks :100:

2022-03-18 09:14 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/open-services-group/community/pull/101#pullrequestreview-914108424" title="Approved">harshad16</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **goern** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @goern` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=open-services-group%2Fcommunity).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/open-services-group/community/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["goern"]} -->

2022-03-21 15:49 UTC, Gregory-Pereira commented
/retest

2022-03-21 15:50 UTC, sesheta commented
@Gregory-Pereira: Cannot trigger testing until a trusted user reviews the PR and leaves an `/ok-to-test` message.

<details>

In response to [this](https://github.com/open-services-group/community/pull/101#issuecomment-1074067003):

>/retest


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-03-22 09:05 UTC, goern commented
/approve

2022-03-22 09:05 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/open-services-group/community/pull/101#issuecomment-1074907144" title="Approved">goern</a>*, *<a href="https://github.com/open-services-group/community/pull/101#pullrequestreview-914108424" title="Approved">harshad16</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=open-services-group%2Fcommunity).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/open-services-group/community/blob/main/OWNERS)~~ [goern]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-03-24 10:11 UTC, tumido approved these changes
/lgtm
/approve

2022-03-24 10:11 UTC, tumido commented
/retest

2022-03-24 10:11 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/open-services-group/community/pull/101#issuecomment-1074907144" title="Approved">goern</a>*, *<a href="https://github.com/open-services-group/community/pull/101#pullrequestreview-914108424" title="Approved">harshad16</a>*, *<a href="https://github.com/open-services-group/community/pull/101#pullrequestreview-920017500" title="Approved">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=open-services-group%2Fcommunity).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/open-services-group/community/blob/main/OWNERS)~~ [goern,tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-03-24 10:24 UTC, merged