prefix url with scheme
open-services-group/community pull request #13
Opened 2022-01-12 14:16 UTC by durandom

otherwise it'll result in a broken link

2022-01-12 14:16 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **durandom** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=open-services-group%2Fcommunity).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/open-services-group/community/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["durandom"]} -->

2022-01-12 16:05 UTC, goern requested changes

2022-01-12 16:05 UTC, goern commented on sigs.yaml
> +    url: http://meet.google.com/qkt-yacp-wzm
is it really http? not https?

2022-01-20 11:09 UTC, durandom commented on sigs.yaml
> +    url: http://meet.google.com/qkt-yacp-wzm
```suggestion
    url: https://meet.google.com/qkt-yacp-wzm
```

2022-01-20 11:09 UTC, durandom commented on sigs.yaml
> +    url: http://meet.google.com/zsu-avba-enx
```suggestion
    url: https://meet.google.com/zsu-avba-enx
```

2022-01-20 12:56 UTC, goern commented
/approve

2022-01-20 12:56 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/open-services-group/community/pull/13#issuecomment-1017479843" title="Approved">goern</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=open-services-group%2Fcommunity).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/open-services-group/community/blob/main/OWNERS)~~ [goern]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-01-20 13:02 UTC, merged