scrum masters
open-services-group/community pull request #246
Opened 2022-07-20 09:44 UTC by durandom

2022-07-20 09:46 UTC, sesheta commented
@durandom: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
peribolos | 172cf15934afcab41bfd66494ccdae91ccfcd778 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/open-services-group_community/246/peribolos/1549692216128049152) | true | `/test peribolos`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=open-services-group&repo=community&pr=246). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Adurandom). Please help us and [open an issue](https://github.com/open-services-group/community/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-07-20 09:49 UTC, durandom commented
@tumido can we use peribolos-as-a-service for this repo?

2022-08-05 11:43 UTC, codificat requested changes
I just saw this PR after sending #251 (which is already merged), sorry.

I think #251 obsoletes the *Scrum* part of this PR - only leaving the move of Shrey pending.

A rebase will be needed in any case...

2022-08-05 11:43 UTC, codificat commented on github-config.yaml
> +        members:
We need everyone on the team as members of the scrum team...

2022-08-05 11:43 UTC, codificat commented on github-config.yaml
> +          scrum: triage
And the team needs more than *triage* permissions to e.g. be able to edit existing issues.

Our usage of the `scrum` repo is not the typical dev repo usage, and editing each other's issues would be expected.

2022-08-05 11:45 UTC, schwesig commented
/kind onboarding

2022-08-05 11:45 UTC, sesheta commented
@schwesig: The label(s) `kind/onboarding` cannot be applied, because the repository doesn't have them.

<details>

In response to [this](https://github.com/open-services-group/community/pull/246#issuecomment-1206355552):

>/kind onboarding


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-10-06 10:24 UTC, closed without merging