feat(sig-services): Introduce Peribolos as a service
open-services-group/community pull request #80
Opened 2022-02-24 16:25 UTC by tumido

Add new sub-project Peribolos as a service

And cleanup some of the sub-projects that we don't have consensus over so far.

2022-02-24 16:25 UTC, tumido commented
/cc sig-services-leads

2022-02-24 16:26 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **tumido** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=open-services-group%2Fcommunity).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/open-services-group/community/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["tumido"]} -->

2022-02-24 16:26 UTC, tumido commented
/assing @Shreyanand

2022-02-24 16:26 UTC, tumido commented
/assign @Shreyanand

2022-02-24 16:42 UTC, sesheta commented
@tumido: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
peribolos | 30e085f00b9e2da961a94ddf52c45d9d20e91244 | [link](https://prow.operate-first.cloud/view/s3/thoth/prow-logs/pr-logs/pull/open-services-group_community/80/peribolos/1496884367123812352) | true | `/test peribolos`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=open-services-group&repo=community&pr=80). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Atumido). Please help us and [open an issue](https://github.com/open-services-group/community/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-24 16:48 UTC, Shreyanand requested changes
lgtm :+1: 
Just one small thing, I guess we'd have to run `podman run --rm --volume $(pwd):/workdir:Z quay.io/open-services-group/community-tooling:v0.1.0-dev` for changing other files as well.

2022-02-24 17:15 UTC, tumido commented
> Just one small thing, I guess we'd have to run `podman run --rm --volume $(pwd):/workdir:Z quay.io/open-services-group/community-tooling:v0.1.0-dev` for changing other files as well.

I did that. I don't think the PR is missing any changes... Or did I miss something?

2022-02-24 17:39 UTC, Shreyanand commented
> I did that. I don't think the PR is missing any changes... Or did I miss something?

The changes look good, got confused as the command changes different files for sig updates than for sub project updates. 

The peribolos test fails though. Wonder why... Happened [here](https://github.com/open-services-group/community/pull/40) as well.

2022-02-24 17:44 UTC, tumido commented
/override peribolos

2022-02-24 17:44 UTC, sesheta commented
@tumido: Overrode contexts on behalf of tumido: peribolos

<details>

In response to [this](https://github.com/open-services-group/community/pull/80#issuecomment-1050102382):

>/override peribolos


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-02-25 12:46 UTC, tumido commented
/approve
/lgtm

2022-02-25 12:46 UTC, sesheta commented
@tumido: you cannot LGTM your own PR.

<details>

In response to [this](https://github.com/open-services-group/community/pull/80#issuecomment-1050823871):

>/approve
>/lgtm


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-02-25 12:46 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/open-services-group/community/pull/80#issuecomment-1050823871" title="LGTM">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=open-services-group%2Fcommunity).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/open-services-group/community/blob/main/OWNERS)~~ [tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-02-25 12:50 UTC, merged